# Generated by Django 5.0.4 on 2024-04-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardholder', models.CharField(max_length=255)),
                ('cardnumber', models.CharField(max_length=16)),
                ('expirydate', models.CharField(max_length=5)),
                ('cvc', models.CharField(max_length=3)),
            ],
        ),
    ]
